# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutcms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'verbose_name_plural': 'taxonomies'},
        ),
    ]
