# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutcms', '0002_auto_20160704_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='registered_taxonomies',
            field=models.ManyToManyField(related_name='registered_terms', related_query_name='registered_term', to='nutcms.Taxonomy'),
        ),
    ]
