# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutcms', '0003_term_registered_taxonomies'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', related_query_name='resource', to='nutcms.Post')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nutcms.Post')),
            ],
        ),
    ]
