# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutcms', '0005_auto_20160713_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieresource',
            old_name='post',
            new_name='entry',
        ),
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', related_query_name='entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='terms',
            field=models.ManyToManyField(related_name='entries', related_query_name='entry', to='nutcms.Term'),
        ),
    ]
